title: Lit Apps
author:
  name: LitRitt
  email: dev@litritt.com
description: The home of some iOS sideload apps
url: "https://apps.litritt.com"

exclude:
  - "update.py"
  - "LICENSE.txt"
  - "README.md"
  - "bucket"
