title: Lit Apps
author:
  name: LitRitt
  email: dev@litritt.com
description: The home of some iOS sideload apps
url: "https://apps.litritt.com"
remote_theme: litritt/lit-midnight

exclude:
  - "update.py"
  - "LICENSE.txt"
  - "README.md"
  
plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

whitelist:
  - jekyll-redirect-from
